### ISSUE TITLE
Add Existing Organizations

### ISSUE THREAD

**Issue by nick4rivers** [OregonStateUniversity/bda-explorer#233]
Need to add existing organizations so that they can be attached to projects. This can be done in the /organizations path.

@cooperphyz and @nueadkie can one of you guys send me the most recent data for the Projects table.

**Comment by nick4rivers** [comment]
Here is a list of projects that could be curated and added as organizations.

[Low-Tech Projects.csv.zip](https://github.com/osu-cascades/bda-explorer/files/8682527/Low-Tech.Projects.csv.zip)

**Comment by ybakos** [comment]
All organizations are in production, audited 10/27/23.
