### ISSUE TITLE
Contact Us: form

### ISSUE THREAD

**Issue by nathanstruhs** [OregonStateUniversity/bda-explorer#57]
Nick Weber: 'Guys, was thinking we need a way for people to reach out with questions about the website or projects? I don't mind if this comes to me? Ideas for placement, maybe in the footer of the landing page?'

**Comment by webernick79** [comment]
Thanks Nathan, all looks good

**Comment by nick4rivers** [comment]
This might be a good one to add as even a final feature. Easy button on the 'about' page to send an email?

**Comment by nick4rivers** [comment]
This could easily be just a send email. Doesn't have to be a form.

**Comment by ybakos** [comment]
@nick4rivers I'm going to add a contact link that is just an email address. On the "about" page and the footer. What email address would you like me to use?

**Comment by ybakos** [comment]
Per NW 10/23/23:

Use NW email address at anabranch.
